### ISSUE TITLE
Doesn't work in combination of reqwest library

### ISSUE THREAD

**Issue by omid** [peterhuene/azure-functions-rs#108]
I used your library and faced an error.
You can see the changed code and also the error in the following link:

https://gist.github.com/omid/b55fe742e8bacff0c34042218de5d363

Any idea about the error?

## Environment information (OS, versions, etc.)
I tested it on Arch and Ubuntu (latest versions + upgrades)
And also tried it on the latest rust nightly

There is a copy of this issue here:
https://github.com/robertohuertasm/azure-function-rust/issues/1

**Comment by peterhuene** [comment]
Hi @omid,

Thanks for reporting this.  Judging by the error, it looks like the linker can't find some exports from OpenSSL.  To better my understanding, what version of OpenSSL is installed on your systems (both Arch and Ubuntu)?  This could also be a breaking change in the `openssl` crate, but it looks like the places where these exports are used have been there for at least a few months.

The CI builds using a Debian Stretch based image and I myself develop using Arch and macOS, but I've been traveling and haven't been able to use my Arch system for over a month now.  I'll try doing so this afternoon and get back to you.

Thanks!

**Comment by omid** [comment]
Hey @peterhuene,

Have a nice trip :-)

OpenSSL version on my Arch is _1.1.1a _
And on my Ubuntu 18.04 is _1.1.0g_

Best

**Comment by peterhuene** [comment]
It appears to be a conflict between `reqwest` (which uses OpenSSL) and `grpcio` (which uses BoringSSL by default).  Azure Functions for Rust uses `grpcio` to communicate with the Azure Functions Host.

It can be easily reproduced by a simple app that depends on both `reqwest` and `grpcio` and creates a `reqwest::Client`.

https://github.com/pingcap/grpc-rs/pull/239 appears to be a related fix.  I'll investigate how best to fix this for Azure Functions for Rust.

**Comment by peterhuene** [comment]
Hi @omid, can you try putting this in your `Cargo.toml` dependencies section?

```
grpcio = {version = "0.4.1", features = ["openssl"] }
```

That should hopefully force grpcio to link against openssl which will make things consistent with `reqwest`.

I'll see about a proper fix in Azure Functions for Rust soon.

**Comment by omid** [comment]
Cool, your last suggestion works fine.
