### ISSUE TITLE
Remove need for nightly or update the documentation.

### ISSUE THREAD

**Issue by ianpurton** [peterhuene/azure-functions-rs#147]
Ideally this should run out of the box on stable 2018 or perhaps specifiy up front that nightly is needed. I got the following after `cargo install azure-functions-sdk`

```
error[E0554]: #![feature] may not be used on the stable release channel
   |
61 | #![feature(rust_2018_preview)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
   |
62 | #![feature(in_band_lifetimes)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by rylev** [comment]
@ianpurton Sorry for this! The current version on crates.io does indeed require nightly but the version in master does not (the requirement was recently removed). We should have handled the transition more smoothly, but a new version will be released to crates.io probably this week.

**Comment by ianpurton** [comment]
@rylev That's great. Thanks.
