### ISSUE TITLE
local.settings.json values are overwritten

### ISSUE THREAD

**Issue by rtyler** [peterhuene/azure-functions-rs#232]
This could be considered a feature request or a bug report :man_shrugging: 

## Steps to reproduce

* Define settings in a `local.settings.json` file in the repo
* `cargo func run`
* Note that function does not run with those settings.

## Expected  behavior

* Settings used for the function run

## Actual behavior

* New settings are written into place

---

Some of the settings which I'm interested in setting would be things like:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": "UseDevelopmentStorage=true"
  },
  "Host": {
    "CORS": "*"
  }
}
```

This would allow me to do local development without a storage account (yay) and allow overriding the CORS setting for local development.

Looking the `create_local_settings_file`, it might make sense to perform a simple hash merge between the desired state and `local.settings.json` were it to be available. Ideally with `IsEncrypted` turned to `true` so I could also define some of my other settings, like an Event Hub connection string :smile_cat: 

I'll use the workaround of manually setting a `--script-root` with `cargo func run` for now, that doesn't seem to overwrite the `local.settings.json` when I copy it in manually.

**Comment by peterhuene** [comment]
Agreed, this is something that needs to be fixed.

While it won't overwrite one if one exists already in the script root, I think the `cargo func run` command should check if one exists locally in the repo root and copy it to the script root (with or without `--script-root` specified).

**Comment by peterhuene** [comment]
Additionally, we should probably just generate `local.settings.json` as part of `cargo func new-app` so that the Rust related settings are present initially.

`cargo func run` can then just copy it into the script-root if it is out of date.  If it doesn't exist in the script root and one doesn't exist locally, we'll create the minimal `local.settings.json` that is needed to get it working for Rust.

**Comment by peterhuene** [comment]
@rtyler would you be interested in fixing this since you've been poking around the code?  If not, no worries.  I think this will be the last thing going into 0.7.0 (punting the `cargo func publish` command to 0.8.0).

**Comment by rtyler** [comment]
@peterhuene what's your timeline for 0.7.0? My Rust skills are rudimentary at best, but I can probably take a whack tonight

**Comment by peterhuene** [comment]
There's no real deadline, so at your convenience.  I was planning on releasing 0.7.0 tomorrow night (PDT), but there's really no rush.

**Comment by rtyler** [comment]
I'll let you know what I figure out after all the usual errands.

It might be useful to configure [Gitter](https://gitter.im) for this repo, if you're open to more real-time chat :smile_cat:

**Comment by peterhuene** [comment]
I've created https://gitter.im/azure-functions-rs/community and have added a badge to the README in `dev`.

**Comment by peterhuene** [comment]
@all-contributors please add @rtyler for code, doc, review, and ideas.
