### ISSUE TITLE
Set the repository's default branch to `dev`

### ISSUE THREAD

**Issue by rtyler** [peterhuene/azure-functions-rs#235]
I'm not sure if you're aware of this feature, but it would make pull requests automatically open targeting `dev` rather than mmaster.

You should be able to change the default branch in this setting :point_down: 

![branch](https://user-images.githubusercontent.com/26594/55675286-409d9d80-5875-11e9-936d-f45690861c87.png)

**Comment by peterhuene** [comment]
I want the default branch to be `master` as that is the branch we release out of and I want the `README` documentation to reflect that; the `README` in dev is considered "in flight" and might not reflect the currently published crates.

Unfortunately, GitHub doesn't have an option to make a branch the default PR target only as far as I am aware.
