### ISSUE TITLE
Investigate using arbitrary token streams in attributes

### ISSUE THREAD

**Issue by rylev** [peterhuene/azure-functions-rs#255]
Starting with Rust 1.34 custom attributes now allow for [arbitrary token streams](https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html#custom-attributes-accept-arbitrary-token-streams). This allows for much cleaner attributes. 

For example, the current `copy_blob` example has the following syntax:

```rust
#[func]
#[binding(name = "_req", route = "copy/blob/{container}/{name}")]
#[binding(name = "blob", path = "{container}/{name}")]
#[binding(name = "output1", path = "{container}/{name}.copy")]
pub fn copy_blob(_req: HttpRequest, blob: Blob) -> (HttpResponse, Blob)
```

With this latest feature, this could be changed to:
```rust
#[func]
#[binding(_req, route = "copy/blob/{container}/{name}")]
#[binding(blob, path = "{container}/{name}")]
#[binding(return.1, path = "{container}/{name}.copy")]
pub fn copy_blob(_req: HttpRequest, blob: Blob) -> (HttpResponse, Blob)
```

I'm not sold on the specific syntax, but I think it warrants investigation.

## Drawbacks

Unfortunately, because this feature was first introduced with 1.34, that would become the minimum required compiler.

**Comment by peterhuene** [comment]
Definitely worth looking into.  Thanks for the suggestion!

**Comment by peterhuene** [comment]
I looked into this feature, and while that would be useful, I do have a preference for the explicit `name` argument for the binding attribute.  While it is a little more verbose than your suggestion, the order of the arguments isn't important and there's no special handling in terms of parsing it the way it is now.

I'm going to close this issue for now, but as there absolutely might be a use for arbitrary tokens for a future UX, we can reopen it for the future as need arises.  Thanks!
