### ISSUE TITLE
SendGridMessage should have a `build` method.

### ISSUE THREAD

**Issue by peterhuene** [peterhuene/azure-functions-rs#282]
Like `HttpResponse`, the `SendGridMessage` binding should have a `build` method that returns the builder.

This will make the API a little more ergonomic, as users won't have to use the builder type from the `send_grid` module.

**Comment by peterhuene** [comment]
@t-eckert this one is pretty straight forward if you want a crack at it :)

**Comment by t-eckert** [comment]
Work being done in this branch of my fork: https://github.com/t-eckert/azure-functions-rs/tree/SendGrid-build--issue282

**Comment by t-eckert** [comment]
Correction: https://github.com/t-eckert/azure-functions-rs/tree/SG-buildfunc

**Comment by peterhuene** [comment]
Closed by #300.
