### ISSUE TITLE
Error to execute cargo func run

### ISSUE THREAD

**Issue by carlosb1** [peterhuene/azure-functions-rs#350]
## Steps to reproduce
If you follow the README steps:
```
cargo func new-app hello
cd hello 
cargo func new http -n hello
cargo build
cargo func run
```
## Expected  behavior
It should start locally

## Actual behavior
But I got this:
```
carlosb@carlosb-UX530UX:~/rust-workspace/hello|master⚡ 
⇒  cargo func run
🚀 spawning 'cargo' to initialize script root: cargo run -- init --script-root /tmp/script-root.rsHpjy4jI4V2 --sync-extensions ️✓
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/hello init --script-root /tmp/script-root.rsHpjy4jI4V2 --sync-extensions`
🚀 spawning 'func' to start the Azure Functions Host: func host start --port 8080 ✗
error: failed to spawn func: No such file or directory (os error 2)
ensure the Azure Functions Core Tools are installed.
carlosb@carlosb-UX530UX:~/rust-workspace/hello|master⚡ 

```

## Environment information (OS, versions, etc.)
Ubuntu Mint 19.1 (Ubuntu 18.04), clean installation, rust nightly 1.38

**Comment by peterhuene** [comment]
Hi @carlosb1.

Did you install the Azure Functions Core Tools and a .NET Core SDK for your platform?

If so, is the `func` tool from the Azure Functions Core Tools on your PATH?

**Comment by carlosb1** [comment]
Sorry... I didn't check the reqs..

**Comment by carlosb1** [comment]
Sorry another time.... I installed all the dependencies:
core net sdk -> https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.301
azure functions library -> https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#linux
And also I verified that I had installed the rust library: 
cargo install azure-functions-sdk

Doing a normal workflow (As a commented in a clean installation), I got:

     Running `target/debug/hello init --script-root /tmp/script-root.QpN4kzj9xkBp --sync-extensions`
🚀 spawning 'func' to start the Azure Functions Host: func host start --port 8080 ️✓
Can't determin project langauge from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]

**Comment by peterhuene** [comment]
I'll take a look.  I really hope the latest version of the core tools didn't break us.

**Comment by peterhuene** [comment]
That appears to be the case.  I'm looking into a workaround while I file a bug on the Azure Functions team.

**Comment by peterhuene** [comment]
@carlosb1 if possible, could you downgrade your `Azure Functions Core Tools` to `2.7.1373`?

I don't know if that's possible with your package manager (I don't use Ubuntu).  If you installed via `npm`, you can do `npm install -g azure-functions-core-tools@2.7.1373`.

That should work around the issue.

**Comment by carlosb1** [comment]
Thanks! I will try...

**Comment by peterhuene** [comment]
I've filed https://github.com/Azure/azure-functions-core-tools/issues/1448 to track the issue with the core tools.

**Comment by carlosb1** [comment]
@peterhuene  with `npm` it works fine!

**Comment by peterhuene** [comment]
Hi @carlosb1.  The Azure Functions Core Tools team have released a new version that should fix the issue.  Please upgrade to 2.7.1480 when you get a chance.

Thanks!
