### ISSUE TITLE
Validate Functions v3 Preview

### ISSUE THREAD

**Issue by brettsam** [peterhuene/azure-functions-rs#436]
Details will be coming soon. Opening issues right now to track. 

Functions v3 preview (on .NET Core 3) is coming soon and we'd like the language worker owners to take it for a spin first and let us know if there are any issues.

Initial plan:
- Build details coming early Mon Oct 7, with a CLI build and a private site extension links.
- Would like some kind of signoff by EOD Wed Oct 9
    - That signoff is up to the language worker owner. Can be a test suite run, or even some manual validation with the CLI and/or production.

**Comment by peterhuene** [comment]
Hi @brettsam.  Thanks for including us in your validation pass.

I will perform a validation on Monday when the instructions are made available.

**Comment by brettsam** [comment]
Some directions and links have been added to https://github.com/Azure/azure-functions-host/issues/5041. Let me know if you run into issues getting set up -- permissions, etc.

**Comment by peterhuene** [comment]
@brettsam thanks for the instructions!  Unfortunately, I don't appear to have access to the CLI zip (I use a public identity of peterhuene@protonmail.com as I'm no longer a Microsoft employee).

**Comment by peterhuene** [comment]
@brettsam alternatively, you may email the CLI zip to that address if it isn't an inconvenience.  Thanks!

**Comment by brettsam** [comment]
Sorry about that! I guess you can't link directly to an artifact in devops. Try going here: https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=2389 and downloading the entire **drop** folder. It's almost 1gb, but that should get you the package you need. I just tried this in an incognito browser, without logging in, and it worked.

![image](https://user-images.githubusercontent.com/1089915/66568230-de706e80-eb1d-11e9-8448-3bc2fce5911a.png)

From inside that zip, you'll use **Azure.Functions.Cli.win-x86.3.0.1719.zip** as the CLI.

**Comment by peterhuene** [comment]
@brettsam Thanks!  I'll get this tested soon and report back.

**Comment by peterhuene** [comment]
Hi @brettsam.  I tested the 3.0 Azure Functions runtime and CLI and I did not discover any new issues.  I'm fairly confident the 3.0 release won't break the Rust worker.

Thanks for including us in the validation pass!  I'm going to close this issue to signal that I'm signing off.
