### ISSUE TITLE
rust:slim is not stretch

### ISSUE THREAD

**Issue by dbcfd** [peterhuene/azure-functions-rs#467]
## Steps to reproduce
Update rust:slim, build a new docker container. 

## Expected  behavior
App runs

## Actual behavior
App will immediately fail due to wrong glibc version.

https://github.com/peterhuene/azure-functions-rs/blob/master/docker/build-image/Dockerfile#L1 should target `rust:1.39-stretch` until `mcr.microsoft.com/dotnet/core/runtime-deps:2.2` is built against buster.

**Comment by peterhuene** [comment]
Thanks for reporting this!

I'll get this fixed and push up a new build image soon.

**Comment by peterhuene** [comment]
@dbcfd Thanks again for reporting this.  I've pushed a new `peterhuene/azure-functions-rs-build:0.11.0` image with the change to Stretch.  I'll close this issue when #468 is merged that fixes the Dockerfile.

**Comment by peterhuene** [comment]
Please let me know if this didn't resolve your issue.  Thanks!

**Comment by dbcfd** [comment]
So ran into one issue with the new image 

`The method driver /usr/lib/apt/methods/https could not be found.`

Removing `/etc/apt/sources.list.d/microsoft-prod.list` allowed me to build as normal, and the new image worked correctly.

**Comment by peterhuene** [comment]
Hi @dbcfd. Do you have repro steps I could follow to reproduce the error?

I had no problems with the image when I tested it before pushing it up, so I'd like to figure out why it didn't work for you.

**Comment by dbcfd** [comment]
```
FROM peterhuene/azure-functions-rs-build:0.11.0 AS build-image

#RUN rm /etc/apt/sources.list.d/microsoft-prod.list

RUN apt-get update \
    && apt-get install -y \
        pkg-config \
        libssl-dev \
        make \
        g++ \
        libsasl2-dev
```
