### ISSUE TITLE
Update or delete Table rows/columns

### ISSUE THREAD

**Issue by cbrevik** [peterhuene/azure-functions-rs#479]
**Is your feature request related to a problem? Please describe.**
I'm using the Table-binding in a function app which works quite well for adding rows. But, I haven't figured out how to update or delete rows, since the `table.rows()` iterator does not return mutable rows.

**Describe the solution you'd like**
I'd love to have some way to mutate the row `Map`, to add/delete/update columns for existing rows, as well as some way of deleting whole rows. I am not versatile enough in Rust to know how the API for this should be designed though.

**Describe alternatives you've considered**
I've considered just adding an additional function app in another language which would support update/delete, and proxy to that from my Rust function app. But I'd rather avoid having to deploy multiple function apps for this use case.

**Additional context**
Tried to do `row.entry(..)` as per `serde_json` docs but didn't work for obvious reasons:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/4932625/70088809-453e6f80-1617-11ea-8731-4ccfb1903cfc.png">

I am not that well-versed in Rust so sorry if I've misunderstood something. 😬

**Comment by peterhuene** [comment]
Hi @cbrevik.

Thanks for reporting this issue.  At the time I wrote the table binding, the [documentation for output table bindings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#output) mentioned that updates weren't supported without directly using the Azure Storage SDK.

I'm not sure if that's entirely accurate after looking at the source for the binding.  I'll have to do some experimentation.  If it's supported, I'll add a mutable iterator (`rows_mut()`) to the Rust API.

Looking over the code for the core implementation of the binding, I think it might, so I need to

**Comment by peterhuene** [comment]
You may be able to workaround this limitation right now by converting the table to a serde_json `Value`, manipulate it, and then convert it back to a table:

```rust
// ...
let mut v: Value = table.into();

// Manipulate the JSON of the table

let t: Table = v.into();
// ...
```

**Comment by peterhuene** [comment]
Ugh, never mind.  It looks like I didn't implement `From<Value>` for `Table`.

**Comment by peterhuene** [comment]
So it appears that the documentation is correct.  The table output binding can't update existing entities in table storage.

Unfortunately, it looks like you'll need to use the [Azure SDK for Rust](https://github.com/MindFlavor/AzureSDKForRust) to modify get and modify the table rows.

It appears that the other extension languages (like JavaScript) also have to do the same.  In C#, you would bind to the `CloudTable` class from the Azure Storage SDK too, I believe.

I'm going to close this issue as "won't fix".  I'm happy to help with using the Azure SDK for Rust; there are examples of using the table storage part of the SDK and you should be able to configure it with the storage account name and key (there doesn't seem to be any support for parsing connection strings, though).

**Comment by cbrevik** [comment]
Thanks for the follow up @peterhuene! Went to bed last night and, woke up to a solution. I hadn't heard about the Azure SDK for Rust before, so I'll definitely check that out.

I've worked with Azure Functions and C# before, but totally forgot that you had to use `CloudTable` for update/delete. 🤦‍♂ 

Opportunity to learn/write more Rust I guess! 😀

**Comment by peterhuene** [comment]
@cbrevik If you do get a function working for update / delete with the Azure SDK, I would absolutely love to include it in the table binding example!  Please feel free to open a PR against the `dev` branch and I'd be happy to review and merge it.

**Comment by cbrevik** [comment]
Sure thing! I'd love to contribute if I get it working.
