### ISSUE TITLE
Log displayed in cargo func run?

### ISSUE THREAD

**Issue by btrepp** [peterhuene/azure-functions-rs#553]
## Steps to reproduce

Add info!("Hello world") to sample functions (for http request)

## Expected  behavior

Hello world would be logged with the request information/somewhere.

## Actual behavior

Only request information is printed to console.

## Environment information (OS, versions, etc.)

Windows 10.

[dependencies]
azure-functions = "0.11.0"
reqwest  = "*"
horrorshow = "0.8.3"
uuid = "0.8.1"
log = "*"

**Comment by btrepp** [comment]
Ah you need to specify loglevel in host.json

Setting it to "Information" made the entries appear. Hopefully this helps someone else!.

**Comment by Fishrock123** [comment]
I'm having this same issue except `host.json` appears to be set correctly:
```json
  
{
    "version": "2.0",
    "fileLoggingMode": "always",
    "logging": {
        "logLevel": {
            "default": "Information",
            "Function": "Information"
        }
    }
}
```
