### ISSUE TITLE
Incoming language worker protocol change related to environment variables.

### ISSUE THREAD

**Issue by peterhuene** [peterhuene/azure-functions-rs#94]
See Azure/azure-functions-language-worker-protobuf#20.

It looks like there will be a request from the host to set the environment variables for the worker process.

For implementation, we can either modify the process' environment or provide access to these variables via a `Context` binding.

**Comment by pragnagopa** [comment]
Implementing `FunctionEnvironmentLoadRequest ` and `FunctionEnvironmentLoadResponse` is not a requirement right now. Default behavior of when a language worker starts is not changing yet. Please see https://github.com/Azure/azure-functions-host/pull/3824  for more details.

**Comment by peterhuene** [comment]
Thanks for letting me know! I'll track the progress to make sure my worker implementation keeps functioning.

**Comment by peterhuene** [comment]
Closing this issue for now as the host isn't yet sending this request for us to handle.
